// <auto-generated />
namespace WiFiData_Data_Update.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeRoomIdToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeRoomIdToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201706270600072_changeRoomIdToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
