// <auto-generated />
namespace WiFiData_Data_Update.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeRoomIdStrLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeRoomIdStrLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201706270605065_changeRoomIdStrLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
